version: "3.7"

services:
  tokplay-node:
    ports:
      - "3000:3000"
    build: ../
    env_file:
      - ../.env
    environment:
      NODE_ENV: "development"
    volumes:
      - ../src:/www/src
    networks:
      - tokplay
    command: npm run dev
    depends_on:
      - tokplay-mongo

  tokplay-mongo:
    image: mongo:6.0.8
    ports:
      - "27017:27017"
    volumes:
      - ./_data/mongo:/data/db
    networks:
      - tokplay

networks:
  tokplay:
